language: python
notifications:
  email: false

matrix:
  include:
#    - python: 2.7
#      dist: xenial
#    - python: 3.3
#      dist: trusty
#    - python: 3.4
#      dist: xenial
    - python: 3.5
      dist: focal
    - python: 3.6
      dist: focal
    - python: 3.7
      dist: focal
    - python: 3.8
      dist: focal

install: "pip install -r dev-requirements.txt"
script: make test
